# Generated by Django 4.0.1 on 2023-06-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
