# Generated by Django 4.2.2 on 2023-06-27 13:25

import customer.models.search.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_category_message_messagedocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentElem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_meet', models.DateTimeField(blank=True, null=True, verbose_name='Назначенная дата')),
                ('judges', models.TextField(verbose_name='Состав судейтсва')),
                ('number', models.CharField(max_length=300, verbose_name='Номер Дела')),
                ('name_court', models.TextField(verbose_name='Название Суда')),
                ('room_court', models.TextField(verbose_name='Зал судебных заседаний')),
                ('involved', models.TextField(verbose_name='Стороны по делу')),
                ('description', models.TextField(verbose_name='Суть Дела')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Cудебное рассмотрение',
                'verbose_name_plural': 'Судебные рассмотрения',
                'ordering': ['dt_meet'],
            },
        ),
        migrations.CreateModel(
            name='CourtAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.BooleanField(default=False, verbose_name='подписка?')),
            ],
            options={
                'verbose_name': 'Поиск Судебного рассмотрения',
                'verbose_name_plural': 'Поиск Судебных рассмотрений',
                'ordering': ['pk'],
            },
        ),
        migrations.RemoveField(
            model_name='minjustcompany',
            name='minjust',
        ),
        migrations.RemoveField(
            model_name='minjustfop',
            name='minjust',
        ),
        migrations.AlterField(
            model_name='bdr',
            name='user',
            field=customer.models.search.base.UserForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bdr', to='user', verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='court',
            name='search',
            field=customer.models.search.base.SearchForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court', to='search', verbose_name='поисковый запрос'),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='search',
            field=customer.models.search.base.SearchForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to='search', verbose_name='поисковый запрос'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='user',
            field=customer.models.search.base.UserForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='user', verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='docstate',
            name='user',
            field=customer.models.search.base.UserForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_state', to='user', verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='inactivedocument',
            name='user',
            field=customer.models.search.base.UserForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactive_doc', to='user', verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='mvs',
            name='search',
            field=customer.models.search.base.SearchForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvs', to='search', verbose_name='поисковый запрос'),
        ),
        migrations.AlterField(
            model_name='search',
            name='user',
            field=customer.models.search.base.UserForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='user', verbose_name='пользователь'),
        ),
        migrations.DeleteModel(
            name='Minjust',
        ),
        migrations.DeleteModel(
            name='MinjustCompany',
        ),
        migrations.DeleteModel(
            name='MinjustFop',
        ),
        migrations.AddField(
            model_name='courtassignment',
            name='search',
            field=customer.models.search.base.SearchForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_assign', to='search', verbose_name='поисковый запрос'),
        ),
        migrations.AddField(
            model_name='assignmentelem',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='customer.court', verbose_name='Cудебное дело'),
        ),
        migrations.AddField(
            model_name='assignmentelem',
            name='court_assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_elem', to='customer.courtassignment', verbose_name='Cудебное рассмотрение'),
        ),
    ]
