# Generated by Django 4.2.2 on 2023-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_assignmentelem_courtassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='en', max_length=200, verbose_name='Название АНГЛ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(default='uk', max_length=200, verbose_name='Название УКР'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(default='en', max_length=200, verbose_name='Название АНГЛ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='name_uk',
            field=models.CharField(default='uk', max_length=200, verbose_name='Название УКР'),
            preserve_default=False,
        ),
    ]
