# Generated by Django 4.2.2 on 2023-07-09 13:14

import customer.models.search.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_category_name_en_category_name_uk_country_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asvpelem',
            name='agency_edrpou',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ЕДРП исполнителя'),
        ),
        migrations.AddField(
            model_name='asvpelem',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AddField(
            model_name='asvpelem',
            name='number',
            field=models.CharField(default='numb', max_length=100, verbose_name='номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asvpelem',
            name='search',
            field=customer.models.search.base.SearchForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='asvp_elem', to='search', verbose_name='поисковый запрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asvpelem',
            name='debtors',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='должник'),
        ),
    ]
