# Generated by Django 4.2.2 on 2023-07-10 13:58

import customer.models.search.base
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from customer.enums import State


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_asvpelem_agency_edrpou_asvpelem_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=State.as_model_choices(), default='national', max_length=16, verbose_name='реестр')),
                ('saved_data', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None, verbose_name='Сохраненная информация')),
                ('user', customer.models.search.base.UserForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_search', to='user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Сохраненный поиск',
                'verbose_name_plural': 'Сохраненные поиски',
            },
        ),
    ]
