# Generated by Django 4.0.1 on 2023-06-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='базовый конфиг LiqPay', max_length=80, verbose_name='название конфига')),
                ('public_key', models.CharField(max_length=100, verbose_name='Public key LiqPay')),
                ('private_key', models.CharField(max_length=100, verbose_name='Private key LiqPay')),
                ('price', models.PositiveIntegerField(default=200, verbose_name='стоимость подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
                ('server_url', models.CharField(default='', help_text='https://your_server_url.com', max_length=200, verbose_name='URL to get status from Liqpay')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
    ]
