# Generated by Django 4.0.1 on 2023-06-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='p_credentials',
            field=models.TextField(blank=True, null=True, verbose_name='Credentials Portmone'),
        ),
        migrations.AddField(
            model_name='config',
            name='p_login',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Login Portmone'),
        ),
        migrations.AddField(
            model_name='config',
            name='p_password',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Password Portmone'),
        ),
        migrations.AddField(
            model_name='config',
            name='p_payee_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='PayeeID Portmone'),
        ),
        migrations.AlterField(
            model_name='config',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный?'),
        ),
        migrations.AlterField(
            model_name='config',
            name='price',
            field=models.PositiveIntegerField(default=200, verbose_name='Стоимость подписки'),
        ),
        migrations.AlterField(
            model_name='config',
            name='private_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Private key LiqPay'),
        ),
        migrations.AlterField(
            model_name='config',
            name='public_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Public key LiqPay'),
        ),
        migrations.AlterField(
            model_name='config',
            name='server_url',
            field=models.CharField(default='', help_text='https://your_server_url.com', max_length=200, verbose_name='URL to get status from Payment'),
        ),
        migrations.AlterField(
            model_name='config',
            name='title',
            field=models.CharField(default='Базовый конфиг', max_length=80, verbose_name='Название конфига'),
        ),
    ]
