# Generated by Django 4.0.1 on 2023-06-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='токен')),
                ('webhook_url', models.CharField(max_length=255, verbose_name='Webhook URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
            ],
            options={
                'verbose_name': 'конфиг',
                'verbose_name_plural': 'конфиги',
            },
        ),
        migrations.CreateModel(
            name='TbotMessagesBotmessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('text_ua', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Тексти повідомлень',
                'verbose_name_plural': 'Текст повідомлення',
                'db_table': 'tbot_messages_botmessage',
            },
        ),
        migrations.CreateModel(
            name='TbotMessagesButton',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('num', models.SmallIntegerField()),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_inline_mode', models.BooleanField(blank=True, null=True)),
                ('callback_data', models.CharField(blank=True, max_length=40, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_reply', models.BooleanField(blank=True, null=True)),
                ('row', models.SmallIntegerField(blank=True, null=True)),
                ('text_en', models.CharField(blank=True, max_length=256, null=True)),
                ('text_ua', models.CharField(blank=True, max_length=256, null=True)),
                ('url_en', models.CharField(blank=True, max_length=200, null=True)),
                ('url_ua', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='tbot_messages.tbotmessagesbotmessage')),
            ],
            options={
                'db_table': 'tbot_messages_button',
            },
        ),
    ]
